@SPC.API_HostAddress = https://localhost:7191

GET {{SPC.API_HostAddress}}/weatherforecast/
Accept: application/json

###

@code=0
GET {{SPC.API_HostAddress}}/api/outils/{code:int}?code={{code}}

###
